require("dotenv").config({ path: __dirname + "/../.env", override: true });
const { GoogleGenAI } = require("@google/genai");
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

async function generateCaption(
  interest,
  captionType = "motivational",
  language,
  targetAudience = "general",
  captionLength = "medium",
  mood = "happy",
  emojiIntensity = "minimal"
) {
  try {
    const requiredParams = {
      interest,
      captionType,
      language,
      targetAudience,
      captionLength,
      mood,
      emojiIntensity,
    };

    for (const [key, value] of Object.entries(requiredParams)) {
      if (value === undefined || value === null) {
        throw new Error(`Missing or invalid parameter: ${key}`);
      }
    }

    const lengthLimits = {
      "very-short": { min: 5, max: 30 },
      short: { min: 30, max: 80 },
      medium: { min: 80, max: 150 },
      long: { min: 150, max: 220 },
      max: { min: 220, max: 280 },
    };

    const { min, max } = lengthLimits[captionLength] || lengthLimits.medium;

    const emojiCounts = {
      none: 0,
      minimal: 1,
      moderate: 2,
      heavy: 3,
    };

    const emojiCount = emojiCounts[emojiIntensity] || 1;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `
You’re ghostwriting a tweet for a chill, witty, slightly burnt-out Gen-Z dev who posts thoughts at 2am.
It should feel like a real person mid-scroll suddenly typed a thought and hit tweet.
Not trying to impress. Not trying to teach. Just tweeting like they always do.

✍️ Instructions:
Topic: About ${interest} — but never name the topic directly

Tone: ${captionType} (dry, sarcastic, introspective, observational, or tired-funny)

Language: ${language} (can mix casual English with Hinglish — just how people actually talk)

Audience: ${targetAudience}

Mood: ${mood}

Length: Strictly between ${min}–${max} characters

Emojis: Exactly ${emojiCount} natural, trendy emoji(s) that match the vibe (${emojiIntensity})

Hashtags: Add 2–3 lowkey hashtags that don’t feel try-hard

📌 Style Rules (Do Not Skip):
lowercase everything unless caps are for emphasis or emotion

zero formatting — no line breaks, no quotation marks, no bullet points

write like it’s a brain dump, not a caption

unpolished is better than perfect

might sound random, tired, cryptic, moody, or self-aware — that’s the point

make it feel posted, not written

🚫 Strict No-Zone:
❌ corporate buzzwords, startup-y phrases, or “inspiring” nonsense

❌ tweets that sound like advice

❌ polished grammar unless it’s for effect

❌ NSFW, political, offensive content

❌ anything that feels like a “growth tweet” or “content strategy”

✅ Goal:
Make the reader feel like

“damn. i tweet like this too.”
or
“bro i felt that.”

Output only the tweet text. No intro. No explanation. No formatting. Just the raw tweet.`,
      config: {
        systemInstruction: `You are an expert at crafting short, raw, and viral-feeling tweets that sound like they were posted impulsively by a real Gen-Z user at 2am — not generated by a machine.

Your tweets should feel personal, casual, and culturally accurate, as if the user was tweeting from their bed while slightly tired, bored, or self-aware.

You write for smart, online-native people. Your tone should reflect accounts like  — mixing dry or dark humor, moody thoughts, subtle flexes, or cryptic one-liners. Always prefer low-effort authenticity over polish.

Your Objectives:

Write 1 tweet that feels completely human, impulsive, and emotionally real

Don’t try to go viral. It should accidentally feel relatable

Prioritize tone and mood matching over clarity or grammar

Parameters to follow strictly:

Topic is related to: ${interest} but never say the topic name

Tone: ${captionType} (e.g., sarcastic, dry, moody, introspective, chaotic)

Language: ${language} — use slang or casual phrasing natural to this

Audience: ${targetAudience}

Mood: ${mood} — reflect it subtly, don’t force it

Length: Between ${min} and ${max} characters

Emojis: Exactly ${emojiCount} trendy emoji(s) that match the vibe,
Hashtags: Add 2–3 only if they feel natural and low-effort (or skip if not needed)

Style: lowercase preferred, no grammar perfection, no formatting, no punchlines, no structured setup

Strictly Avoid:

robotic phrasing

motivational quotes or generic life lessons

corporate voice, overexplaining, or “advice-giving” tone

sounding like it was “written” instead of “posted”

political, sensitive, or NSFW content

Output Rule:

Only output the tweet text.
No explanations. No formatting. No extra notes.
Just the tweet — like it was copied straight from a real timeline.`,
      },
    });

    return response.text;
  } catch (error) {
    throw new error();
  }
}

module.exports = {
  generateCaption,
};
